"""
End-to-end smoke/integration tests for PRAMIGO, run against the tiny synthetic
dataset generated by simulate_data.py (3 groups x 3 patients, 2 omics x 20
features, 10 differentially-expressed features per omic).

Starts from environment creation: the test suite provisions its own fresh venv
using the exact commands documented in README.md (`uv venv --python 3.8` +
`uv pip install -r env/biomixhgt_env.txt`), then runs every subsequent stage -
loading, training (+ resume), saving outputs, and visualization - through THAT
interpreter, for both a 2-group and a 3-group condition setup. This validates
the documented setup instructions themselves, not just the code assuming
dependencies are already present. Both group scenarios reuse the exact same
simulated omic matrices; only the metadata's CONDITION labels differ (the
2-group version merges GroupB and GroupC), so a single
`python src/simulate_data.py` run covers both.

Run manually with:
    pytest src/test_biomix_pipeline.py -v -s

This is a slow integration test - provisioning the environment plus both
pipeline runs takes a few minutes even on this toy-sized data - not something
to run in a tight edit/test loop. Requires the simulated data to exist first:
`python src/simulate_data.py`. Requires `uv` on PATH; environment-setup tests
skip (rather than fail) if it isn't available.
"""
import os
import sys
import shutil
import subprocess

import pandas as pd
import numpy as np
import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(REPO_ROOT, "src")
SIM_DATA_DIR = os.path.join(REPO_ROOT, "data", "simulated_toy")
BIOMIX_SCRIPT = os.path.join(SRC_DIR, "biomix_hgt.py")
ENV_REQUIREMENTS = os.path.join(REPO_ROOT, "env", "biomixhgt_env.txt")

METADATA_3GROUP = os.path.join(SIM_DATA_DIR, "simulated_metadata.tsv")
OMIC1_PATH = os.path.join(SIM_DATA_DIR, "simulated_omic1.tsv")
OMIC2_PATH = os.path.join(SIM_DATA_DIR, "simulated_omic2.tsv")
GROUND_TRUTH_PATH = os.path.join(SIM_DATA_DIR, "simulated_ground_truth.tsv")

N_SAMPLES = 9
N_FEATURES_PER_OMIC = 20
N_DE_PER_OMIC = 10

# Hyperparameters tuned for a 9-sample, 20-feature-per-omic toy dataset. The script's
# defaults (--n_batch 25, --omic*_corr_cutoff 0.7) would either divide the per-batch
# feature counts down to zero (gene_num/metabo_num = int(20/25) = 0) or leave the tiny
# correlation-based graph nearly disconnected - both would break the run outright.
FAST_HPARAMS = [
    "--epoch", "4",
    "--n_batch", "2",
    "--n_hid", "8",
    "--ae_n_hid", "8",
    "--n_heads", "2",
    "--n_layers", "2",
    "--omic1_corr_cutoff", "0.3",
    "--omic2_corr_cutoff", "0.3",
    "--leiden_min_cluster_size", "2",
    "--cuda", "1",
    "--checkpoint_every", "1",
]


def make_two_group_metadata(out_path):
    """Derives a 2-condition metadata file from the 3-group simulated metadata by
    merging GroupB and GroupC into one label. Reuses the exact same omic matrices as
    the 3-group scenario, so only the grouping structure changes between the two."""
    metadata = pd.read_csv(METADATA_3GROUP, sep="\t")
    metadata["CONDITION"] = metadata["CONDITION"].replace({"GroupC": "GroupB"})
    metadata.to_csv(out_path, sep="\t", index=False)
    return str(out_path)


def run_biomix(python_executable, metadata_path, result_dir, extra_args=None):
    """Runs the real biomix_hgt.py script as a subprocess (it's a flat script with
    no importable functions/main guard, so subprocess is the only way to exercise it
    end-to-end), through the given interpreter - normally the one provisioned by
    `provisioned_python` below, not whatever interpreter happens to be running pytest.
    `extra_args` are appended after FAST_HPARAMS, so passing e.g. ["--epoch", "2"]
    overrides FAST_HPARAMS's --epoch via argparse's last-value-wins."""
    cmd = [
        str(python_executable), BIOMIX_SCRIPT,
        "--metadata_path", str(metadata_path),
        "--omic1_path", OMIC1_PATH,
        "--omic2_path", OMIC2_PATH,
        "--result_dir", str(result_dir),
    ] + FAST_HPARAMS + (extra_args or [])
    return subprocess.run(cmd, cwd=SRC_DIR, capture_output=True, text=True, timeout=900)


def _assert_success(proc):
    assert proc.returncode == 0, (
        f"biomix_hgt.py exited with code {proc.returncode}.\n"
        f"--- stdout (tail) ---\n{proc.stdout[-3000:]}\n"
        f"--- stderr (tail) ---\n{proc.stderr[-3000:]}"
    )


# ---------------------------------------------------------------------------
# Environment provisioning: create the venv exactly as README.md documents, and
# hand its interpreter to every other fixture/test in this file. Session-scoped
# so it's provisioned once and reused, not once per test.
# ---------------------------------------------------------------------------
@pytest.fixture(scope="session")
def provisioned_python(tmp_path_factory):
    uv = shutil.which("uv")
    if uv is None:
        pytest.skip("`uv` is not on PATH; cannot provision the environment as documented in README.md")

    venv_dir = tmp_path_factory.mktemp("hgt_env")
    create_proc = subprocess.run(
        [uv, "venv", str(venv_dir), "--python", "3.8"],
        capture_output=True, text=True, timeout=300
    )
    assert create_proc.returncode == 0, (
        f"`uv venv --python 3.8` failed.\nstdout: {create_proc.stdout}\nstderr: {create_proc.stderr}"
    )

    python_exe = venv_dir / ("Scripts" if os.name == "nt" else "bin") / ("python.exe" if os.name == "nt" else "python")
    assert python_exe.exists(), f"Expected a venv interpreter at {python_exe} after `uv venv`"

    install_proc = subprocess.run(
        [uv, "pip", "install", "--python", str(python_exe), "-r", ENV_REQUIREMENTS],
        capture_output=True, text=True, timeout=900
    )
    assert install_proc.returncode == 0, (
        f"`uv pip install -r env/biomixhgt_env.txt` failed.\n"
        f"stdout: {install_proc.stdout[-3000:]}\nstderr: {install_proc.stderr[-3000:]}"
    )
    return str(python_exe)


class TestEnvironmentSetup:
    """Validates the README's documented setup steps actually work, independent of
    anything pipeline-specific - if these fail, the problem is the environment/
    dependency pins, not biomix_hgt.py's logic."""

    def test_uv_is_available(self):
        assert shutil.which("uv") is not None, "uv is required to follow the README's documented setup instructions"

    def test_venv_creation_and_dependency_install_succeeds(self, provisioned_python):
        assert os.path.exists(provisioned_python)

    def test_key_dependencies_importable_in_provisioned_env(self, provisioned_python):
        check = subprocess.run(
            [provisioned_python, "-c",
             "import torch, torch_geometric, igraph, leidenalg, umap, plotly, "
             "pandas, numpy, sklearn, networkx, matplotlib, seaborn; print('IMPORT_OK')"],
            capture_output=True, text=True, timeout=120
        )
        assert check.returncode == 0 and "IMPORT_OK" in check.stdout, (
            f"stdout: {check.stdout}\nstderr: {check.stderr}"
        )


@pytest.fixture(scope="module")
def three_group_run(provisioned_python, tmp_path_factory):
    result_dir = tmp_path_factory.mktemp("three_group_result")
    proc = run_biomix(provisioned_python, METADATA_3GROUP, result_dir)
    return proc, result_dir


@pytest.fixture(scope="module")
def two_group_run(provisioned_python, tmp_path_factory):
    result_dir = tmp_path_factory.mktemp("two_group_result")
    metadata_dir = tmp_path_factory.mktemp("two_group_metadata")
    metadata_2g = make_two_group_metadata(metadata_dir / "simulated_metadata_2group.tsv")
    proc = run_biomix(provisioned_python, metadata_2g, result_dir)
    return proc, result_dir


# ---------------------------------------------------------------------------
# 0. Loading: validate the simulated inputs themselves, independent of the
#    pipeline, so a failure here points at the data rather than at the model.
# ---------------------------------------------------------------------------
class TestSimulatedDataLoading:

    def test_simulated_files_exist(self):
        for path in [METADATA_3GROUP, OMIC1_PATH, OMIC2_PATH, GROUND_TRUTH_PATH]:
            assert os.path.exists(path), f"Missing simulated input: {path}. Run `python src/simulate_data.py` first."

    def test_metadata_has_required_columns_and_three_groups(self):
        metadata = pd.read_csv(METADATA_3GROUP, sep="\t")
        assert {"ID", "CONDITION"}.issubset(metadata.columns)
        assert len(metadata) == N_SAMPLES
        assert metadata["CONDITION"].nunique() == 3
        assert (metadata["CONDITION"].value_counts() == 3).all()

    def test_two_group_metadata_derivation_merges_to_two_conditions(self, tmp_path):
        two_group_path = make_two_group_metadata(tmp_path / "meta2.tsv")
        metadata = pd.read_csv(two_group_path, sep="\t")
        assert len(metadata) == N_SAMPLES  # same samples, just relabeled
        assert metadata["CONDITION"].nunique() == 2

    def test_omic_matrices_align_with_metadata_and_have_expected_shape(self):
        metadata = pd.read_csv(METADATA_3GROUP, sep="\t")
        for path in [OMIC1_PATH, OMIC2_PATH]:
            omic_df = pd.read_csv(path, sep="\t")
            assert omic_df.columns[0] == "ID"
            assert set(omic_df.columns[1:]) == set(metadata["ID"])
            assert omic_df.shape[0] == N_FEATURES_PER_OMIC

    def test_omic_matrices_are_row_normalized(self):
        """Each feature (row) should be ~zero-mean, unit-variance across samples,
        since biomix_hgt.py expects pre-normalized input and does no normalization
        of its own."""
        for path in [OMIC1_PATH, OMIC2_PATH]:
            omic_df = pd.read_csv(path, sep="\t")
            values = omic_df.iloc[:, 1:].values
            #assert (values.mean(axis=1) == pytest.approx(0, abs=1e-6)).all()
            #assert (values.std(axis=1) == pytest.approx(1, abs=1e-6)).all()
            assert np.allclose(values.mean(axis=1), 0, atol=1e-6)
            assert np.allclose(values.std(axis=1), 1, atol=1e-6)

    def test_ground_truth_marks_exactly_ten_de_features_per_omic(self):
        ground_truth = pd.read_csv(GROUND_TRUTH_PATH, sep="\t")
        for omic in ["omic1", "omic2"]:
            de_count = ground_truth[
                (ground_truth["Omic"] == omic) & (ground_truth["Is_Differentially_Expressed"])
            ].shape[0]
            assert de_count == N_DE_PER_OMIC


# ---------------------------------------------------------------------------
# Parametrized end-to-end checks, run once each for the 2-group and 3-group scenario.
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("run_fixture_name", ["two_group_run", "three_group_run"])
class TestPipelineEndToEnd:

    def test_process_completes_successfully(self, request, run_fixture_name):
        proc, _ = request.getfixturevalue(run_fixture_name)
        _assert_success(proc)

    def test_training_checkpoint_and_loss_history_saved(self, request, run_fixture_name):
        _, result_dir = request.getfixturevalue(run_fixture_name)
        checkpoint_path = os.path.join(result_dir, "model", "checkpoint_latest.pt")
        assert os.path.exists(checkpoint_path), "Training checkpoint was not saved"

        loss_dir = os.path.join(result_dir, "loss")
        loss_files = os.listdir(loss_dir)
        assert any("total_losses" in f for f in loss_files), "Total loss history CSV missing"
        assert any("val_losses" in f for f in loss_files), "Validation loss history CSV missing"

        total_losses = pd.read_csv(os.path.join(loss_dir, [f for f in loss_files if "total_losses" in f][0]))
        assert len(total_losses) == 4  # matches FAST_HPARAMS --epoch 4

    def test_embeddings_saved_with_expected_shapes(self, request, run_fixture_name):
        # Per-omic output dirs are named after each omic's manifest `name` (see
        # omics_manifest.py / biomix_hgt.py's `omic_dirs`), not hardcoded "gene"/
        # "metabo" - run_biomix() uses the legacy --omic1_path/--omic2_path flags,
        # which manifest_from_legacy_args() wraps into a 2-entry manifest named
        # "omic1"/"omic2", so those are the directories a run actually creates.
        _, result_dir = request.getfixturevalue(run_fixture_name)
        omic1_files = os.listdir(os.path.join(result_dir, "omic1"))
        omic2_files = os.listdir(os.path.join(result_dir, "omic2"))
        sample_files = os.listdir(os.path.join(result_dir, "sample"))
        assert len(omic1_files) == 1 and len(omic2_files) == 1 and len(sample_files) == 1

        omic1_matrix = pd.read_csv(os.path.join(result_dir, "omic1", omic1_files[0]), sep=" ", header=None)
        assert omic1_matrix.shape[0] == N_FEATURES_PER_OMIC
        omic2_matrix = pd.read_csv(os.path.join(result_dir, "omic2", omic2_files[0]), sep=" ", header=None)
        assert omic2_matrix.shape[0] == N_FEATURES_PER_OMIC
        sample_matrix = pd.read_csv(os.path.join(result_dir, "sample", sample_files[0]), sep=" ", header=None)
        assert sample_matrix.shape[0] == N_SAMPLES

    def test_attention_csv_saved(self, request, run_fixture_name):
        _, result_dir = request.getfixturevalue(run_fixture_name)
        att_files = [f for f in os.listdir(os.path.join(result_dir, "att")) if f.endswith(".csv")]
        assert len(att_files) == 1
        att_df = pd.read_csv(os.path.join(result_dir, "att", att_files[0]))
        assert att_df.shape[0] > 0, "Attention edge table is empty"

    def test_core_visualizations_saved(self, request, run_fixture_name):
        _, result_dir = request.getfixturevalue(run_fixture_name)
        plots_dir = os.path.join(result_dir, "plots")
        expected_always = [
            "training_loss_components.pdf",
            "Confusion_matrix_figure.pdf",
            "Interpretability_nodes_attention_figure.pdf",
            "embeddings_evaluations_figure.pdf",
            "network_interactive.html",
        ]
        for filename in expected_always:
            assert os.path.exists(os.path.join(plots_dir, filename)), f"Missing expected output: {filename}"

    def test_leiden_cluster_outputs_if_any_cluster_formed(self, request, run_fixture_name):
        """With only 40 total candidate features, whether Leiden finds any cluster
        >= --leiden_min_cluster_size is data/seed-dependent (topology of a tiny
        correlation graph). This check is intentionally tolerant: if the pipeline
        itself reported no valid clusters, it skips rather than failing."""
        proc, result_dir = request.getfixturevalue(run_fixture_name)
        if ("no clusters passed the minimum size filter" in proc.stdout
                or "no connected top-feature subgraph found" in proc.stdout):
            pytest.skip("No Leiden clusters formed for this toy dataset/seed - nothing to check.")
        plots_dir = os.path.join(result_dir, "plots")
        for filename in [
            "leiden_clusters_composition.csv",
            "leiden_cluster_network.pdf",
            "leiden_cluster_subgraphs.pdf",
            "leiden_program_activity_scores.csv",
            "leiden_program_activity_report.pdf",
        ]:
            assert os.path.exists(os.path.join(plots_dir, filename)), f"Missing expected output: {filename}"

    def test_supplementary_visualizations_saved(self, request, run_fixture_name):
        _, result_dir = request.getfixturevalue(run_fixture_name)
        supplementary_dir = os.path.join(result_dir, "supplementary")
        expected = [
            "loss_lr_schedule.pdf", "loss_component_share.pdf",
            "roc_curves.pdf", "per_class_performance.pdf",
            "attention_concentration_by_omic.pdf", "attention_distribution_by_omic.pdf",
            "embedding_separability_silhouette.pdf", "embedding_pca_scree.pdf",
            "network_hub_nodes.pdf",
        ]
        for filename in expected:
            assert os.path.exists(os.path.join(supplementary_dir, filename)), f"Missing supplementary output: {filename}"


# ---------------------------------------------------------------------------
# Resume/checkpoint feature: train partially, resume, and confirm training
# actually continued from the checkpoint rather than restarting from epoch 0.
# ---------------------------------------------------------------------------
class TestResumeTraining:

    def test_resume_continues_past_the_checkpointed_epoch(self, provisioned_python, tmp_path):
        result_dir = tmp_path / "resume_result"

        first_pass = run_biomix(provisioned_python, METADATA_3GROUP, result_dir, extra_args=["--epoch", "2"])
        _assert_success(first_pass)
        loss_dir = os.path.join(result_dir, "loss")
        first_file = [f for f in os.listdir(loss_dir) if "total_losses" in f][0]
        assert len(pd.read_csv(os.path.join(loss_dir, first_file))) == 2

        second_pass = run_biomix(provisioned_python, METADATA_3GROUP, result_dir, extra_args=["--epoch", "4", "--resume"])
        _assert_success(second_pass)
        assert "Resuming HGT training from checkpoint" in second_pass.stdout
        assert "Resumed at epoch 2" in second_pass.stdout

        second_file = [f for f in os.listdir(loss_dir) if "total_losses" in f][0]
        second_losses = pd.read_csv(os.path.join(loss_dir, second_file))
        assert len(second_losses) == 4, "Resumed run should carry the full 4-epoch loss history, not just the resumed 2"

    def test_resume_flag_without_existing_checkpoint_falls_back_to_fresh_training(self, provisioned_python, tmp_path):
        result_dir = tmp_path / "resume_no_checkpoint_result"
        proc = run_biomix(provisioned_python, METADATA_3GROUP, result_dir, extra_args=["--epoch", "2", "--resume"])
        _assert_success(proc)
        assert "no checkpoint was found" in proc.stdout

    def test_resume_past_completed_training_exits_cleanly(self, provisioned_python, tmp_path):
        """Resuming with --epoch <= the checkpoint's completed epoch has nothing to
        do (the rest of the script depends on the training loop having executed at
        least once) - it should exit(0) with a clear message, not crash later on
        with a confusing NameError."""
        result_dir = tmp_path / "resume_already_done_result"
        first_pass = run_biomix(provisioned_python, METADATA_3GROUP, result_dir, extra_args=["--epoch", "2"])
        _assert_success(first_pass)

        second_pass = run_biomix(provisioned_python, METADATA_3GROUP, result_dir, extra_args=["--epoch", "2", "--resume"])
        assert second_pass.returncode == 0
        assert "Nothing to resume" in second_pass.stdout


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-v"]))
